Importacao de bibliotecas

In [1]:
!pip install PyPDF2

Collecting PyPDF2
  Downloading pypdf2-3.0.1-py3-none-any.whl.metadata (6.8 kB)
Downloading pypdf2-3.0.1-py3-none-any.whl (232 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 3.6 MB/s eta 0:00:00
Installing collected packages: PyPDF2
Successfully installed PyPDF2-3.0.1

In [2]:
!pip install chardet

Requirement already satisfied: chardet in /usr/local/lib/python3.11/dist-packages (5.2.0)

In [3]:
!pip install pdfplumber

Collecting pdfplumber
  Downloading pdfplumber-0.11.6-py3-none-any.whl.metadata (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.8/42.8 kB 1.6 MB/s eta 0:00:00
Collecting pdfminer.six==20250327 (from pdfplumber)
  Downloading pdfminer_six-20250327-py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: Pillow>=9.1 in /usr/local/lib/python3.11/dist-packages (from pdfplumber) (11.1.0)
Collecting pypdfium2>=4.18.0 (from pdfplumber)
  Downloading pypdfium2-4.30.1-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.2/48.2 kB 3.3 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from pdfminer.six==20250327->pdfplumber) (3.4.1)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.11/dist-packages (from pdfminer.six==20250327->pdfplumber) (43.0.3)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.11/dist-packages (from cryptography>=36.0.0->pdfminer.six==20250327->pdfplumber) (1.17.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20250327->pdfplumber) (2.22)
Downloading pdfplumber-0.11.6-py3-none-any.whl (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.2/60.2 kB 4.2 MB/s eta 0:00:00
Downloading pdfminer_six-20250327-py3-none-any.whl (5.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 59.9 MB/s eta 0:00:00
Downloading pypdfium2-4.30.1-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 68.3 MB/s eta 0:00:00
Installing collected packages: pypdfium2, pdfminer.six, pdfplumber
Successfully installed pdfminer.six-20250327 pdfplumber-0.11.6 pypdfium2-4.30.1

In [15]:
!pip install bertopic

Collecting bertopic
  Downloading bertopic-0.17.0-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: hdbscan>=0.8.29 in /usr/local/lib/python3.11/dist-packages (from bertopic) (0.8.40)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.11/dist-packages (from bertopic) (2.0.2)
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.11/dist-packages (from bertopic) (2.2.2)
Requirement already satisfied: plotly>=4.7.0 in /usr/local/lib/python3.11/dist-packages (from bertopic) (5.24.1)
Requirement already satisfied: scikit-learn>=1.0 in /usr/local/lib/python3.11/dist-packages (from bertopic) (1.6.1)
Requirement already satisfied: sentence-transformers>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from bertopic) (3.4.1)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.11/dist-packages (from bertopic) (4.67.1)
Requirement already satisfied: umap-learn>=0.5.0 in /usr/local/lib/python3.11/dist-packages (from bertopic) (0.5.7)
Requirement already satisfied: scipy>=1.0 in /usr/local/lib/python3.11/dist-packages (from hdbscan>=0.8.29->bertopic) (1.14.1)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.11/dist-packages (from hdbscan>=0.8.29->bertopic) (1.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.1.5->bertopic) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from plotly>=4.7.0->bertopic) (9.1.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from plotly>=4.7.0->bertopic) (24.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.0->bertopic) (3.6.0)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=0.4.1->bertopic) (4.51.3)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=0.4.1->bertopic) (2.6.0+cu124)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=0.4.1->bertopic) (0.30.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=0.4.1->bertopic) (11.1.0)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.11/dist-packages (from umap-learn>=0.5.0->bertopic) (0.60.0)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.11/dist-packages (from umap-learn>=0.5.0->bertopic) (0.5.13)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2025.3.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2.32.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (4.13.2)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.11/dist-packages (from numba>=0.51.2->umap-learn>=0.5.0->bertopic) (0.43.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic) (1.17.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.1.6)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.3.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.5.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2025.1.31)
Downloading bertopic-0.17.0-py3-none-any.whl (150 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.6/150.6 kB 5.2 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.4 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 68.8 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 57.7 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 39.4 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.1 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 6.1 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 12.5 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.4 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.8 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 85.5 MB/s eta 0:00:00
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, bertopic
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed bertopic-0.17.0 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127

In [16]:
!pip install fitz

Collecting fitz
  Downloading fitz-0.0.1.dev2-py2.py3-none-any.whl.metadata (816 bytes)
Collecting configobj (from fitz)
  Downloading configobj-5.0.9-py2.py3-none-any.whl.metadata (3.2 kB)
Collecting configparser (from fitz)
  Downloading configparser-7.2.0-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: httplib2 in /usr/local/lib/python3.11/dist-packages (from fitz) (0.22.0)
Requirement already satisfied: nibabel in /usr/local/lib/python3.11/dist-packages (from fitz) (5.3.2)
Collecting nipype (from fitz)
  Downloading nipype-1.10.0-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from fitz) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from fitz) (2.2.2)
Collecting pyxnat (from fitz)
  Downloading pyxnat-1.6.3-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from fitz) (1.14.1)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /usr/local/lib/python3.11/dist-packages (from httplib2->fitz) (3.2.3)
Requirement already satisfied: importlib-resources>=5.12 in /usr/local/lib/python3.11/dist-packages (from nibabel->fitz) (6.5.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.11/dist-packages (from nibabel->fitz) (24.2)
Requirement already satisfied: typing-extensions>=4.6 in /usr/local/lib/python3.11/dist-packages (from nibabel->fitz) (4.13.2)
Requirement already satisfied: click>=6.6.0 in /usr/local/lib/python3.11/dist-packages (from nipype->fitz) (8.1.8)
Requirement already satisfied: networkx>=2.5 in /usr/local/lib/python3.11/dist-packages (from nipype->fitz) (3.4.2)
Collecting prov>=1.5.2 (from nipype->fitz)
  Downloading prov-2.0.1-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: pydot>=1.2.3 in /usr/local/lib/python3.11/dist-packages (from nipype->fitz) (3.0.4)
Requirement already satisfied: python-dateutil>=2.2 in /usr/local/lib/python3.11/dist-packages (from nipype->fitz) (2.8.2)
Collecting rdflib>=5.0.0 (from nipype->fitz)
  Downloading rdflib-7.1.4-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: simplejson>=3.8.0 in /usr/local/lib/python3.11/dist-packages (from nipype->fitz) (3.20.1)
Collecting traits>=6.2 (from nipype->fitz)
  Downloading traits-7.0.2-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.8 kB)
Requirement already satisfied: filelock>=3.0.0 in /usr/local/lib/python3.11/dist-packages (from nipype->fitz) (3.18.0)
Collecting acres (from nipype->fitz)
  Downloading acres-0.3.0-py3-none-any.whl.metadata (5.5 kB)
Collecting etelemetry>=0.3.1 (from nipype->fitz)
  Downloading etelemetry-0.3.1-py3-none-any.whl.metadata (3.2 kB)
Collecting looseversion!=1.2 (from nipype->fitz)
  Downloading looseversion-1.3.0-py2.py3-none-any.whl.metadata (4.6 kB)
Collecting puremagic (from nipype->fitz)
  Downloading puremagic-1.28-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->fitz) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->fitz) (2025.2)
Requirement already satisfied: lxml>=4.3 in /usr/local/lib/python3.11/dist-packages (from pyxnat->fitz) (5.3.2)
Requirement already satisfied: requests>=2.20 in /usr/local/lib/python3.11/dist-packages (from pyxnat->fitz) (2.32.3)
Requirement already satisfied: pathlib>=1.0 in /usr/local/lib/python3.11/dist-packages (from pyxnat->fitz) (1.0.1)
Collecting ci-info>=0.2 (from etelemetry>=0.3.1->nipype->fitz)
  Downloading ci_info-0.3.0-py3-none-any.whl.metadata (6.1 kB)
Collecting rdflib>=5.0.0 (from nipype->fitz)
  Downloading rdflib-6.3.2-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.2->nipype->fitz) (1.17.0)
Collecting isodate<0.7.0,>=0.6.0 (from rdflib>=5.0.0->nipype->fitz)
  Downloading isodate-0.6.1-py2.py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.20->pyxnat->fitz) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.20->pyxnat->fitz) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.20->pyxnat->fitz) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.20->pyxnat->fitz) (2025.1.31)
Downloading fitz-0.0.1.dev2-py2.py3-none-any.whl (20 kB)
Downloading configobj-5.0.9-py2.py3-none-any.whl (35 kB)
Downloading configparser-7.2.0-py3-none-any.whl (17 kB)
Downloading nipype-1.10.0-py3-none-any.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 28.5 MB/s eta 0:00:00
Downloading pyxnat-1.6.3-py3-none-any.whl (95 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.4/95.4 kB 7.3 MB/s eta 0:00:00
Downloading etelemetry-0.3.1-py3-none-any.whl (6.4 kB)
Downloading looseversion-1.3.0-py2.py3-none-any.whl (8.2 kB)
Downloading prov-2.0.1-py3-none-any.whl (421 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 421.5/421.5 kB 13.4 MB/s eta 0:00:00
Downloading rdflib-6.3.2-py3-none-any.whl (528 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 528.1/528.1 kB 23.2 MB/s eta 0:00:00
Downloading traits-7.0.2-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 61.2 MB/s eta 0:00:00
Downloading acres-0.3.0-py3-none-any.whl (10 kB)
Downloading puremagic-1.28-py3-none-any.whl (43 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.2/43.2 kB 2.5 MB/s eta 0:00:00
Downloading ci_info-0.3.0-py3-none-any.whl (7.8 kB)
Downloading isodate-0.6.1-py2.py3-none-any.whl (41 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.7/41.7 kB 2.7 MB/s eta 0:00:00
Installing collected packages: puremagic, looseversion, traits, isodate, configparser, configobj, ci-info, acres, rdflib, pyxnat, etelemetry, prov, nipype, fitz
Successfully installed acres-0.3.0 ci-info-0.3.0 configobj-5.0.9 configparser-7.2.0 etelemetry-0.3.1 fitz-0.0.1.dev2 isodate-0.6.1 looseversion-1.3.0 nipype-1.10.0 prov-2.0.1 puremagic-1.28 pyxnat-1.6.3 rdflib-6.3.2 traits-7.0.2

In [4]:
import os
import re
import sqlite3
import chardet  # Para detectar o encoding

In [5]:
def create_database(db_path):
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    cursor.execute('''CREATE TABLE IF NOT EXISTS relatorio (
                        numero_relatorio TEXT PRIMARY KEY,
                        data TEXT
                        )''')

    for topico in ['A', 'B', 'C', 'D']:
        cursor.execute(f'''CREATE TABLE IF NOT EXISTS topico_{topico} (
                            id INTEGER PRIMARY KEY AUTOINCREMENT,
                            numero_relatorio TEXT,
                            paragrafo TEXT,
                            FOREIGN KEY (numero_relatorio) REFERENCES relatorio(numero_relatorio))
                            ''')

    conn.commit()
    conn.close()

In [6]:
create_database("relatorio.db")

In [7]:
def extrair_dados_arquivo(nome_arquivo):
    """
    Extrai a data e o número do relatório a partir do nome do arquivo.
    Exemplo de nome de arquivo: 2020_09_COPOM233 -> data: 2020_09, número: 233
    """
    match = re.search(r'(\d{4}_\d{2})_COPOM(\d+)', nome_arquivo)
    if match:
        data = match.group(1)
        numero_relatorio = match.group(2)
        return numero_relatorio, data
    return None, None

In [8]:
def processar_arquivos(diretorio, db_path):
    """
    Lê todos os arquivos do diretório, extrai as informações e insere na tabela relatorio.
    """
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    for arquivo in os.listdir(diretorio):
        numero_relatorio, data = extrair_dados_arquivo(arquivo)

        if numero_relatorio and data:
            try:
                cursor.execute('''INSERT INTO relatorio (numero_relatorio, data)
                                  VALUES (?, ?)''', (numero_relatorio, data))
            except sqlite3.IntegrityError:
                print(f"Relatório {numero_relatorio} já existe no banco de dados.")

    conn.commit()
    conn.close()

In [9]:
# @title ## Importando dados
import pandas as pd
import os
import numpy as np
from google.colab import drive

drive.mount('/content/drive')

caminho_dados = '/content/drive/Shareddrives/IC - Otimizacao computacional para inflacao/Extracao_topicos'

# Listar os arquivos dentro da pasta "Dados"
arquivos_dados = os.listdir(caminho_dados)

print(arquivos_dados)

Mounted at /content/drive
['Relatorio-COPOM', 'extracao_pdf.ipynb']

In [11]:
# Executar a função para processar os arquivos no diretório "Copom-relatorios"
caminho = os.path.join(caminho_dados, "Relatorio-COPOM")
processar_arquivos(caminho, "relatorio.db")

In [14]:
#exemplo dos dados
def pegar_dois_primeiros(db_path):
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    # Executar a query
    cursor.execute("SELECT * FROM relatorio")

    # Obter os nomes das colunas
    colunas = [desc[0] for desc in cursor.description]

    # Obter os resultados
    resultados = cursor.fetchall()

    conn.close()

    # Exibir os resultados com os nomes das colunas
    for registro in resultados:
        print(dict(zip(colunas, registro)))

# Executar a função
pegar_dois_primeiros("relatorio.db")

{'numero_relatorio': '268', 'data': '2025_01'}
{'numero_relatorio': '267', 'data': '2024_12'}
{'numero_relatorio': '266', 'data': '2024_11'}
{'numero_relatorio': '265', 'data': '2024_09'}
{'numero_relatorio': '264', 'data': '2024_07'}
{'numero_relatorio': '263', 'data': '2024_06'}
{'numero_relatorio': '262', 'data': '2024_05'}
{'numero_relatorio': '261', 'data': '2024_03'}
{'numero_relatorio': '260', 'data': '2024_01'}
{'numero_relatorio': '259', 'data': '2023_12'}
{'numero_relatorio': '258', 'data': '2023_11'}
{'numero_relatorio': '257', 'data': '2023_09'}
{'numero_relatorio': '256', 'data': '2023_08'}
{'numero_relatorio': '255', 'data': '2023_06'}
{'numero_relatorio': '254', 'data': '2023_05'}
{'numero_relatorio': '253', 'data': '2023_03'}
{'numero_relatorio': '252', 'data': '2023_02'}
{'numero_relatorio': '251', 'data': '2022_12'}
{'numero_relatorio': '250', 'data': '2022_10'}
{'numero_relatorio': '249', 'data': '2022_09'}
{'numero_relatorio': '248', 'data': '2022_08'}
{'numero_relatorio': '247', 'data': '2022_06'}
{'numero_relatorio': '246', 'data': '2022_05'}
{'numero_relatorio': '245', 'data': '2022_03'}
{'numero_relatorio': '244', 'data': '2022_02'}
{'numero_relatorio': '243', 'data': '2021_12'}
{'numero_relatorio': '242', 'data': '2021_10'}
{'numero_relatorio': '241', 'data': '2021_09'}
{'numero_relatorio': '240', 'data': '2021_08'}
{'numero_relatorio': '239', 'data': '2021_06'}
{'numero_relatorio': '238', 'data': '2021_05'}
{'numero_relatorio': '237', 'data': '2021_03'}
{'numero_relatorio': '236', 'data': '2021_01'}
{'numero_relatorio': '200', 'data': '2016_07'}
{'numero_relatorio': '201', 'data': '2016_08'}
{'numero_relatorio': '202', 'data': '2016_10'}
{'numero_relatorio': '203', 'data': '2016_11'}
{'numero_relatorio': '204', 'data': '2017_01'}
{'numero_relatorio': '205', 'data': '2017_02'}
{'numero_relatorio': '206', 'data': '2017_04'}
{'numero_relatorio': '207', 'data': '2017_05'}
{'numero_relatorio': '208', 'data': '2017_07'}
{'numero_relatorio': '209', 'data': '2017_09'}
{'numero_relatorio': '210', 'data': '2017_10'}
{'numero_relatorio': '211', 'data': '2017_12'}
{'numero_relatorio': '212', 'data': '2018_02'}
{'numero_relatorio': '213', 'data': '2018_03'}
{'numero_relatorio': '214', 'data': '2018_05'}
{'numero_relatorio': '215', 'data': '2018_06'}
{'numero_relatorio': '216', 'data': '2018_08'}
{'numero_relatorio': '217', 'data': '2018_09'}
{'numero_relatorio': '218', 'data': '2018_10'}
{'numero_relatorio': '219', 'data': '2018_12'}
{'numero_relatorio': '220', 'data': '2019_02'}
{'numero_relatorio': '221', 'data': '2019_03'}
{'numero_relatorio': '222', 'data': '2019_05'}
{'numero_relatorio': '223', 'data': '2019_06'}
{'numero_relatorio': '224', 'data': '2019_07'}
{'numero_relatorio': '225', 'data': '2019_09'}
{'numero_relatorio': '226', 'data': '2019_10'}
{'numero_relatorio': '227', 'data': '2019_12'}
{'numero_relatorio': '228', 'data': '2020_02'}
{'numero_relatorio': '229', 'data': '2020_03'}
{'numero_relatorio': '230', 'data': '2020_05'}
{'numero_relatorio': '231', 'data': '2020_06'}
{'numero_relatorio': '232', 'data': '2020_08'}
{'numero_relatorio': '233', 'data': '2020_09'}
{'numero_relatorio': '234', 'data': '2020_10'}
{'numero_relatorio': '235', 'data': '2020_12'}

**Extracao do texto**

In [ ]:
import os
import re
import fitz  # PyMuPDF
import pdfplumber

import re
from collections import defaultdict

import nltk
from nltk.corpus import stopwords
import string

from bertopic import BERTopic
from sentence_transformers import SentenceTransformer

WARNING:tensorflow:From C:\Users\bruno\AppData\Local\Programs\Python\Python311\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [ ]:
"""
    Lê todos os arquivos PDF do diretório e extrai o texto, armazenando
    em um dicionário onde a chave é o número do relatório.
    Se PyMuPDF falhar, tenta com pdfplumber.
    Exibe quais arquivos foram processados com sucesso ou falharam.
"""
def extrair_texto_pdfs(diretorio):
    textos_relatorios = {}
    sucesso = 0  # Contador de arquivos extraídos com sucesso
    erro = 0     # Contador de arquivos com falha
    erros_detectados = []  # Lista para armazenar os arquivos com erro

    for arquivo in os.listdir(diretorio):
        numero_relatorio, _ = extrair_dados_arquivo(arquivo)  # Extrai número

        if numero_relatorio:
            caminho_pdf = os.path.join(diretorio, arquivo)
            texto_final = None  # Armazena o texto extraído

            # Primeiro, tenta com PyMuPDF
            try:
                with fitz.open(caminho_pdf) as pdf:
                    texto_extraido = [pagina.get_text("text") for pagina in pdf]
                    texto_final = "\n".join(texto_extraido)

                if not texto_final.strip():  # Se o texto estiver vazio, tenta outro método
                    raise ValueError("Texto vazio extraído com PyMuPDF")

            except Exception as e:
                print(f"⚠️ Falha com PyMuPDF no arquivo {arquivo}: {e}")

                # Se PyMuPDF falhar, tenta pdfplumber
                try:
                    with pdfplumber.open(caminho_pdf) as pdf:
                        texto_extraido = [pagina.extract_text() for pagina in pdf.pages if pagina.extract_text()]
                        texto_final = "\n".join(texto_extraido)

                    if not texto_final.strip():  # Verifica se ainda está vazio
                        raise ValueError("Texto vazio extraído com pdfplumber")

                except Exception as e2:
                    erro += 1
                    erros_detectados.append((arquivo, str(e2)))
                    print(f"❌ Erro ao processar {arquivo} com pdfplumber: {e2}")
                    continue  # Pula para o próximo arquivo

            # Se chegou até aqui, conseguiu extrair o texto corretamente
            textos_relatorios[numero_relatorio] = texto_final
            sucesso += 1
            print(f"✅ Extraído com sucesso: {arquivo}")

            # Detecta possível texto em múltiplas colunas
            if "\n\n" in texto_final[:500]:  # Olha apenas no começo do texto
                print(f"🔍 O arquivo {arquivo} pode ter múltiplas colunas.")

    # Exibe resumo final
    print(f"\n📊 Resumo: {sucesso} arquivos extraídos com sucesso, {erro} arquivos com erro.\n")

    # Lista de arquivos com erro
    if erros_detectados:
        print("❌ Arquivos com erro:")
        for arq, motivo in erros_detectados:
            print(f"- {arq}: {motivo}")

    return textos_relatorios

In [ ]:
def extrair_dados_arquivo(nome_arquivo):
    """
    Extrai o número do relatório do nome do arquivo.
    Exemplo: '2020_09_COPOM233.pdf' -> numero: 233
    """
    match = re.search(r'(\d{4}_\d{2})_COPOM(\d+)', nome_arquivo)
    if match:
        return match.group(2), match.group(1)  # (numero_relatorio, data)
    return None, None

In [ ]:
# Executar a função para extrair textos
textos_extraidos = extrair_texto_pdfs("Copom-relatorios")

In [ ]:
def dividir_texto_em_partes(textos_relatorios, frases_busca):
    """
    Divide o texto de cada relatório em 4 partes com base nas frases encontradas.

    Parâmetros:
    - textos_relatorios: dicionário {numero_relatorio: texto}
    - frases_busca: lista de frases que definem as divisões

    Retorna:
    - Dicionário {numero_relatorio: {parte_1: "texto", parte_2: "texto", ...}}
    """
    resultados_divididos = {}

    for numero_relatorio, texto in textos_relatorios.items():
        # Encontra as posições das frases no texto
        posicoes = []
        for frase in frases_busca:
            match = re.search(re.escape(frase), texto)
            if match:
                posicoes.append((match.start(), frase))

        # Ordena pela posição no texto
        posicoes.sort()

        if not posicoes:
            continue  # Se nenhuma frase foi encontrada, pula o relatório

        # Cria as divisões do texto
        partes = {}
        total_frases = len(posicoes)

        for i in range(4):
            if i < total_frases:
                inicio = posicoes[i][0]
                fim = posicoes[i + 1][0] if i + 1 < total_frases else len(texto)
                partes[f"parte_{i+1}"] = texto[inicio:fim].strip()
            else:
                partes[f"parte_{i+1}"] = ""  # Caso não tenha 4 partes, preenche com vazio

        resultados_divididos[numero_relatorio] = partes

        print(f"📄 Relatório {numero_relatorio} dividido em 4 partes!")

    return resultados_divididos

In [ ]:
# Exemplo de uso:
frases_para_buscar = [
    "A)",
    "B) Riscos",
    "B) Cenários",
    "C) Discussão",
    "D) Decisão"
]

textos_divididos = dividir_texto_em_partes(textos_extraidos, frases_para_buscar)

In [ ]:
def criar_dataframe_secoes(textos_divididos):
    """
    Cria um DataFrame separando os textos por seções, com base nos números do tipo '24.'

    Parâmetros:
    - textos_divididos: dicionário {numero_relatorio: {parte_1: "texto", parte_2: "texto", ...}}

    Retorna:
    - DataFrame com as colunas ["texto", "parte", "relatorio"]
    """
    dados = []

    for numero_relatorio, partes in textos_divididos.items():
        for parte, texto in partes.items():
            # Divide o texto pelas seções que começam com números seguidos de ponto (ex: "24.")
            secoes = re.split(r'\n(\d+\.)', texto)

            if len(secoes) > 1:
                # Reconstruir as seções corretamente
                secoes_formatadas = [secoes[i] + secoes[i+1] for i in range(1, len(secoes)-1, 2)]
            else:
                secoes_formatadas = [texto]  # Caso não tenha seções, mantém o texto inteiro

            # Adicionar ao DataFrame
            for secao in secoes_formatadas:
                dados.append({
                    "texto": secao.strip(),
                    "parte": parte,
                    "relatorio": numero_relatorio
                })

    df = pd.DataFrame(dados, columns=["texto", "parte", "relatorio"])

    return df

                                               texto    parte relatorio
0  1.  Alguns indicadores divulgados desde a últi...  parte_1       200
1  2.  Entretanto, a economia segue operando com ...  parte_1       200
2  3.  No âmbito externo, à decisão do Reino Unid...  parte_1       200
3  4.  Voltando à economia doméstica, índices de ...  parte_1       200
4  5.  As projeções condicionais5 nos cenários pa...  parte_1       200

In [ ]:
# Criar o DataFrame
df_secoes = criar_dataframe_secoes(textos_divididos)

# Exibir as primeiras linhas
print(df_secoes.head())

In [ ]:

# Baixar stopwords do NLTK (apenas necessário uma vez)
nltk.download('stopwords')

In [ ]:
def remover_stopwords(texto):
    """
    Remove as stopwords e pontuações do texto.
    """
    stop_words = set(stopwords.words('portuguese'))  # Stopwords em português
    palavras = texto.split()  # Quebra o texto em palavras
    palavras_filtradas = [palavra for palavra in palavras if palavra.lower() not in stop_words]  # Remove stop-words
    texto_limpo = " ".join(palavras_filtradas)  # Junta novamente as palavras
    return texto_limpo

In [ ]:
# Criar um novo DataFrame com as frases otimizadas
df_secoes["texto_limpo"] = df_secoes["texto"].apply(remover_stopwords)

# Exibir as primeiras linhas do novo DataFrame
print(df_secoes.head())

In [ ]:
# Criando DataFrames separados para cada parte
df_parte1 = df_secoes[df_secoes["parte"] == "parte_1"].copy()
df_parte2 = df_secoes[df_secoes["parte"] == "parte_2"].copy()
df_parte3 = df_secoes[df_secoes["parte"] == "parte_3"].copy()
df_parte4 = df_secoes[df_secoes["parte"] == "parte_4"].copy()

# Exibir quantos registros ficaram em cada parte
print(f"Tamanho das tabelas geradas:")
print(f"Parte 1: {len(df_parte1)} registros")
print(f"Parte 2: {len(df_parte2)} registros")
print(f"Parte 3: {len(df_parte3)} registros")
print(f"Parte 4: {len(df_parte4)} registros")

Tamanho das tabelas geradas:
Parte 1: 452 registros
Parte 2: 424 registros
Parte 3: 638 registros
Parte 4: 315 registros

In [ ]:
# Modelo de embeddings mais moderno
modelo_transformer = SentenceTransformer("all-MiniLM-L6-v2")

In [ ]:
"""
    Aplica BERTopic para extração de tópicos em um DataFrame de textos.

    Parâmetros:
    - df_textos: DataFrame com a coluna 'texto'.
    - nome_parte: Nome da parte para referência.

    Retorna:
    - df_topicos: DataFrame com os tópicos extraídos.
    """

def extrair_topicos(df_textos, nome_parte, n_palavras=5):

    if df_textos.empty:
        print(f"⚠️ Nenhum texto encontrado para {nome_parte}.")
        return df_textos.assign(topico=None, palavras_topico=None)

    textos = df_textos["texto"].tolist()  # Coletar textos

    # Criar e ajustar modelo BERTopic
    modelo = BERTopic(embedding_model=modelo_transformer, verbose=True)
    topicos, _ = modelo.fit_transform(textos)

    # Criar DataFrame com os resultados
    df_topicos = df_textos.copy()
    df_topicos["topico"] = topicos

    # Coletar palavras-chave dos tópicos
    topicos_info = modelo.get_topic_info().set_index("Topic")["Representation"].to_dict()
    df_topicos["palavras_topico"] = df_topicos["topico"].map(lambda t: ", ".join(topicos_info.get(t, [])[:n_palavras]))

    print(f"✅ Extração de tópicos concluída para {nome_parte}!")

    return df_topicos

In [ ]:
import sqlite3
import pandas as pd
from bertopic import BERTopic

def extrair_topicos_bd(nome_banco, modelo_transformer, n_palavras=5):
    # Conectar ao banco
    conn = sqlite3.connect(nome_banco)

    # Listar as tabelas a serem processadas
    tabelas = {
        "parte1_dados": "Parte 1",
        "parte2_dados": "Parte 2",
        "parte3_dados": "Parte 3",
        "parte4_dados": "Parte 4"
    }

    resultados = []

    for tabela, parte in tabelas.items():
        print(f"📌 Processando {tabela}...")

        # Carregar dados da tabela
        df = pd.read_sql(f"SELECT texto, texto_limpo, numero_relatorio FROM {tabela}", conn)

        if df.empty:
            print(f"⚠️ Nenhum dado encontrado em {tabela}. Pulando...")
            continue

        # Aplicar BERTopic na coluna 'texto_limpo'
        modelo = BERTopic(embedding_model=modelo_transformer, verbose=True)
        topicos, _ = modelo.fit_transform(df["texto_limpo"].tolist())

        # Obter palavras-chave dos tópicos
        topicos_info = modelo.get_topic_info().set_index("Topic")["Representation"].to_dict()
        palavras_topico = [", ".join(topicos_info.get(t, [])[:n_palavras]) for t in topicos]

        # Adicionar os resultados ao DataFrame
        df["topico"] = topicos
        df["palavras_topico"] = palavras_topico
        df["parte"] = parte  # Adicionar a informação da parte

        # Guardar no consolidado
        resultados.append(df)

        print(f"✅ Extração concluída para {tabela}!")

    conn.close()

    # Concatenar os resultados em um único DataFrame
    if resultados:
        df_final = pd.concat(resultados, ignore_index=True)
        return df_final
    else:
        return pd.DataFrame(columns=["texto", "texto_limpo", "numero_relatorio", "topico", "palavras_topico", "parte"])

# Exemplo de uso:
df_resultado = extrair_topicos_bd("relatorio.db", modelo_transformer)
df_resultado.to_csv("topicos_extraidos.csv", index=False)

📌 Processando parte1_dados...

2025-02-27 12:10:15,275 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/15 [00:00<?, ?it/s]

2025-02-27 12:10:45,070 - BERTopic - Embedding - Completed ✓
2025-02-27 12:10:45,071 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-02-27 12:11:12,438 - BERTopic - Dimensionality - Completed ✓
2025-02-27 12:11:12,443 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-02-27 12:11:12,550 - BERTopic - Cluster - Completed ✓
2025-02-27 12:11:12,739 - BERTopic - Representation - Extracting topics from clusters using representation models.
2025-02-27 12:11:13,297 - BERTopic - Representation - Completed ✓
2025-02-27 12:11:13,396 - BERTopic - Embedding - Transforming documents to embeddings.

✅ Extração concluída para parte1_dados!
📌 Processando parte2_dados...

Batches:   0%|          | 0/14 [00:00<?, ?it/s]

2025-02-27 12:11:36,151 - BERTopic - Embedding - Completed ✓
2025-02-27 12:11:36,152 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-02-27 12:11:36,627 - BERTopic - Dimensionality - Completed ✓
2025-02-27 12:11:36,628 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-02-27 12:11:36,650 - BERTopic - Cluster - Completed ✓
2025-02-27 12:11:36,654 - BERTopic - Representation - Extracting topics from clusters using representation models.
2025-02-27 12:11:36,717 - BERTopic - Representation - Completed ✓
2025-02-27 12:11:36,881 - BERTopic - Embedding - Transforming documents to embeddings.

✅ Extração concluída para parte2_dados!
📌 Processando parte3_dados...

Batches:   0%|          | 0/20 [00:00<?, ?it/s]

2025-02-27 12:12:11,778 - BERTopic - Embedding - Completed ✓
2025-02-27 12:12:11,779 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-02-27 12:12:12,947 - BERTopic - Dimensionality - Completed ✓
2025-02-27 12:12:12,950 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-02-27 12:12:12,990 - BERTopic - Cluster - Completed ✓
2025-02-27 12:12:12,996 - BERTopic - Representation - Extracting topics from clusters using representation models.
2025-02-27 12:12:13,098 - BERTopic - Representation - Completed ✓
2025-02-27 12:12:13,333 - BERTopic - Embedding - Transforming documents to embeddings.

✅ Extração concluída para parte3_dados!
📌 Processando parte4_dados...

Batches:   0%|          | 0/10 [00:00<?, ?it/s]

2025-02-27 12:12:27,514 - BERTopic - Embedding - Completed ✓
2025-02-27 12:12:27,515 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-02-27 12:12:27,917 - BERTopic - Dimensionality - Completed ✓
2025-02-27 12:12:27,919 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-02-27 12:12:27,942 - BERTopic - Cluster - Completed ✓
2025-02-27 12:12:27,950 - BERTopic - Representation - Extracting topics from clusters using representation models.
2025-02-27 12:12:27,998 - BERTopic - Representation - Completed ✓

✅ Extração concluída para parte4_dados!

In [ ]:
def mostrar_primeiros_elementos(df_resultado):
    if df_resultado.empty:
        print("⚠️ O DataFrame está vazio. Nenhum dado para exibir.")
        return

    # Obter as partes únicas
    partes = df_resultado["parte"].unique()

    for parte in partes:
        print(f"\n📌 {parte} - Primeiros 5 elementos:")
        display(df_resultado[df_resultado["parte"] == parte].head())

# Exemplo de uso:
mostrar_primeiros_elementos(df_resultado)

📌 Parte 1 - Primeiros 5 elementos:

,texto,texto_limpo,numero_relatorio,topico,palavras_topico,parte
0,1. Alguns indicadores divulgados desde a últi...,1. Alguns indicadores divulgados desde última ...,200,3,"atividade, econômica, brasileira, indicadores,...",Parte 1
1,"2. Entretanto, a economia segue operando com ...","2. Entretanto, economia segue operando nível e...",200,5,"capacidade, operando, utilização, refletido, d...",Parte 1
2,"3. No âmbito externo, à decisão do Reino Unid...","3. âmbito externo, decisão Reino Unido sair Un...",200,0,"economias, externo, ambiente, países, emergentes",Parte 1
3,"4. Voltando à economia doméstica, índices de ...","4. Voltando economia doméstica, índices preços...",200,1,"inflação, componentes, sensíveis, ciclo, monet...",Parte 1
4,5. As projeções condicionais5 nos cenários pa...,5. projeções condicionais5 cenários inflação p...,200,1,"inflação, componentes, sensíveis, ciclo, monet...",Parte 1

📌 Parte 2 - Primeiros 5 elementos:

,texto,texto_limpo,numero_relatorio,topico,palavras_topico,parte
452,9. Há riscos de curto prazo para a inflação n...,9. riscos curto prazo inflação Brasil. elevaçã...,200,0,"inflação, comitê, maior, se, preços",Parte 2
453,"10. Adicionalmente, \npor \num \nlado, \nperí...","10. Adicionalmente, lado, períodos prolongados...",200,0,"inflação, comitê, maior, se, preços",Parte 2
454,11. O \nprocesso \nde \nimplantação \ndos \na...,11. processo implantação ajustes necessários e...,200,0,"inflação, comitê, maior, se, preços",Parte 2
455,12. Há riscos inerentes à condução da polític...,12. riscos inerentes condução política monetár...,200,0,"inflação, comitê, maior, se, preços",Parte 2
456,9. Há riscos de curto prazo para a inflação n...,9. riscos curto prazo inflação Brasil. elevaçã...,201,0,"inflação, comitê, maior, se, preços",Parte 2

📌 Parte 3 - Primeiros 5 elementos:

,texto,texto_limpo,numero_relatorio,topico,palavras_topico,parte
876,13. Os membros do Comitê concordaram que houv...,13. membros Comitê concordaram melhora percept...,200,1,"atividade, disponíveis, econômica, recuperação...",Parte 3
877,"14. No que tange à conjuntura internacional, ...","14. tange conjuntura internacional, alguns mem...",200,9,"internacional, economias, global, cenário, cen...",Parte 3
878,"15. Entretanto, todos os membros do Comitê \n...","15. Entretanto, todos membros Comitê destacara...",200,-1,"inflação, comitê, monetária, política, copom",Parte 3
879,16. Todos os membros do Comitê enfatizaram q...,16. Todos membros Comitê enfatizaram continuid...,200,-1,"inflação, comitê, monetária, política, copom",Parte 3
880,17. O debate sobre o balanço de riscos para a...,17. debate sobre balanço riscos inflação focou...,200,17,"desinflação, inflação, hiato, serviços, produto",Parte 3

📌 Parte 4 - Primeiros 5 elementos:

,texto,texto_limpo,numero_relatorio,topico,palavras_topico,parte
1514,"19. O Copom concluiu que, tomados em conjunto...","19. Copom concluiu que, tomados conjunto, cená...",200,11,"2018, viés, monetária, condução, redução",Parte 4
1515,"20. Diante disso, o Copom decidiu, por unanim...","20. Diante disso, Copom decidiu, unanimidade, ...",200,4,"goldfajn, corrêa, sidnei, marques, ilan",Parte 4
1516,"19. Considerando o cenário básico, o balanço ...","19. Considerando cenário básico, balanço risco...",201,10,"básico, balanço, riscos, cenário, unanimidade",Parte 4
1517,20. O Comitê avalia que uma flexibilização das...,20. Comitê avalia flexibilização condições mon...,201,0,"inflação, monetária, reunião, flexibilização, ...",Parte 4
1518,21. O Comitê antecipa que a avaliação dos impa...,21. Comitê antecipa avaliação impactos evoluçã...,201,0,"inflação, monetária, reunião, flexibilização, ...",Parte 4

In [ ]:
def contar_topicos(df_resultado):
    if df_resultado.empty:
        print("⚠️ O DataFrame está vazio. Nenhum dado para contar.")
        return

    # Obter as partes únicas
    partes = df_resultado["parte"].unique()

    for parte in partes:
        print(f"\n📌 {parte} - Contagem de Tópicos:")

        # Filtrar a parte específica
        df_parte = df_resultado[df_resultado["parte"] == parte]

        # Contar a frequência de cada tópico
        contagem = df_parte["topico"].value_counts()

        # Exibir a contagem
        display(contagem.to_frame().reset_index().rename(columns={"index": "topico", "topico": "quantidade"}))

# Exemplo de uso:
contar_topicos(df_resultado)

📌 Parte 1 - Contagem de Tópicos:

    quantidade  count
0            0    120
1            1     53
2            2     52
3            3     48
4            4     30
5            5     29
6            6     24
7            7     22
8            8     21
9            9     18
10          10     14
11          11     13
12          -1      8

📌 Parte 2 - Contagem de Tópicos:

    quantidade  count
0            0    115
1            1     54
2           -1     41
3            2     41
4            3     30
5            4     27
6            5     24
7            6     19
8            7     18
9            8     16
10           9     15
11          10     13
12          11     11

📌 Parte 3 - Contagem de Tópicos:

    quantidade  count
0           -1    174
1            0     49
2            1     45
3            2     43
4            3     32
5            4     31
6            5     29
7            6     29
8            7     27
9            8     26
10           9     25
11          10     23
12          11     19
13          12     17
14          13     16
15          14     16
16          15     14
17          16     13
18          17     10

📌 Parte 4 - Contagem de Tópicos:

    quantidade  count
0            0     54
1            1     48
2           -1     44
3            2     24
4            3     22
5            4     21
6            5     18
7            6     16
8            7     16
9            8     14
10           9     14
11          10     13
12          11     11

In [ ]:
def contar_topicos(df_topicos, nome_parte):
    """
    Conta a quantidade de tópicos únicos extraídos em um DataFrame.

    Parâmetros:
    - df_topicos: DataFrame contendo a coluna 'topico'.
    - nome_parte: Nome da parte analisada.

    Retorna:
    - Número de tópicos únicos.
    """
    num_topicos = df_topicos["topico"].nunique()
    print(f"📊 {nome_parte}: {num_topicos} tópicos extraídos.")
    return num_topicos

# Contar os tópicos para cada parte
topicos_parte1 = contar_topicos(df_topicos_parte1, "Parte 1")
topicos_parte2 = contar_topicos(df_topicos_parte2, "Parte 2")
topicos_parte3 = contar_topicos(df_topicos_parte3, "Parte 3")
topicos_parte4 = contar_topicos(df_topicos_parte4, "Parte 4")

# Resumo geral
print("\n📌 Resumo final:")
print(f"Parte 1: {topicos_parte1} tópicos")
print(f"Parte 2: {topicos_parte2} tópicos")
print(f"Parte 3: {topicos_parte3} tópicos")
print(f"Parte 4: {topicos_parte4} tópicos")

📊 Parte 1: 13 tópicos extraídos.
📊 Parte 2: 12 tópicos extraídos.
📊 Parte 3: 12 tópicos extraídos.
📊 Parte 4: 12 tópicos extraídos.

📌 Resumo final:
Parte 1: 13 tópicos
Parte 2: 12 tópicos
Parte 3: 12 tópicos
Parte 4: 12 tópicos

In [ ]:
# Remover a coluna 'parte' dos DataFrames
df_topicos_parte1 = df_topicos_parte1.drop(columns=['parte'])
df_topicos_parte2 = df_topicos_parte2.drop(columns=['parte'])
df_topicos_parte3 = df_topicos_parte3.drop(columns=['parte'])
df_topicos_parte4 = df_topicos_parte4.drop(columns=['parte'])

In [ ]:
def contar_topicos_por_relatorio_com_groupby(df):
    """
    Conta quantas vezes cada tópico apareceu para um determinado relatório
    e parte, agrupado por relatório e parte.

    Parâmetros:
    - df: DataFrame contendo as colunas 'texto', 'relatorio', 'topico'.

    Retorna:
    - DataFrame com a contagem de tópicos para cada relatório e parte.
    """
    # Agrupar pelo número do relatório e pela parte, e contar a quantidade de cada tópico
    topicos_contagem = df.groupby(['relatorio', 'topico']).size().reset_index(name='contagem')

    # Exibe o resultado agrupado
    print(topicos_contagem)

    return topicos_contagem

# Exemplo de uso para o DataFrame completo com as 4 partes
contagem_topicos_parte1 = contar_topicos_por_relatorio_com_groupby(df_topicos_parte1)

    relatorio  topico  contagem
0         200       0         1
1         200       1         1
2         200       2         1
3         200       3         2
4         200       4         1
..        ...     ...       ...
367       267       3         1
368       267       7         1
369       268       0         2
370       268       3         1
371       268       7         1

[372 rows x 3 columns]

In [ ]:
def contar_topicos(df):
    """
    Conta a quantidade de vezes que cada tópico apareceu em um DataFrame.

    Parâmetros:
    - df: DataFrame contendo as colunas 'topico' (e outras, como 'relatorio' e 'parte').

    Retorna:
    - DataFrame com a contagem de tópicos.
    """
    # Agrupar pelo tópico e contar quantas vezes cada tópico apareceu
    topicos_contagem = df.groupby('topico').size().reset_index(name='contagem')

    # Exibe o resultado
    print(topicos_contagem)

    return topicos_contagem

# Exemplo de uso para os DataFrames das 4 partes
contagem_topicos_parte1 = contar_topicos(df_topicos_parte1)
contagem_topicos_parte2 = contar_topicos(df_topicos_parte2)
contagem_topicos_parte3 = contar_topicos(df_topicos_parte3)
contagem_topicos_parte4 = contar_topicos(df_topicos_parte4)

    topico  contagem
0       -1        14
1        0       114
2        1        59
3        2        47
4        3        40
5        4        32
6        5        30
7        6        28
8        7        24
9        8        21
10       9        17
11      10        15
12      11        11
    topico  contagem
0       -1        36
1        0       106
2        1        48
3        2        42
4        3        37
5        4        36
6        5        34
7        6        23
8        7        21
9        8        16
10       9        14
11      10        11
    topico  contagem
0       -1        55
1        0       331
2        1        50
3        2        31
4        3        28
5        4        24
6        5        23
7        6        23
8        7        22
9        8        19
10       9        18
11      10        14
    topico  contagem
0       -1        15
1        0        78
2        1        48
3        2        28
4        3        27
5        4        23
6        5        21
7        6        20
8        7        17
9        8        15
10       9        12
11      10        11

In [ ]:
import sqlite3

def salvar_contagem_topicos(db_path, topicos_contagem_parte1, topicos_contagem_parte2, topicos_contagem_parte3, topicos_contagem_parte4):
    """
    Salva as contagens de tópicos em 4 tabelas dentro de um banco de dados SQLite.

    Parâmetros:
    - db_path: Caminho do banco de dados SQLite.
    - topicos_contagem_parte1, topicos_contagem_parte2, topicos_contagem_parte3, topicos_contagem_parte4: DataFrames com a contagem de tópicos.
    """
    # Conectar ao banco de dados SQLite
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    # Criar tabelas para armazenar as contagens de tópicos se não existirem
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS parte1_topicos (
            topico TEXT,
            contagem INTEGER
        )
    ''')

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS parte2_topicos (
            topico TEXT,
            contagem INTEGER
        )
    ''')

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS parte3_topicos (
            topico TEXT,
            contagem INTEGER
        )
    ''')

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS parte4_topicos (
            topico TEXT,
            contagem INTEGER
        )
    ''')

    # Função para inserir os dados na tabela correspondente
    def salvar_topicos(df, parte):
        for _, row in df.iterrows():
            cursor.execute(f'''
                INSERT INTO {parte}_topicos (topico, contagem)
                VALUES (?, ?)
            ''', (row['topico'], row['contagem']))

    # Salvar as contagens para cada parte
    salvar_topicos(topicos_contagem_parte1, 'parte1')
    salvar_topicos(topicos_contagem_parte2, 'parte2')
    salvar_topicos(topicos_contagem_parte3, 'parte3')
    salvar_topicos(topicos_contagem_parte4, 'parte4')

    # Commit das alterações e fechamento da conexão
    conn.commit()
    conn.close()

# Exemplo de uso
salvar_contagem_topicos('relatorio.db', contagem_topicos_parte1, contagem_topicos_parte2, contagem_topicos_parte3, contagem_topicos_parte4)

In [ ]:
import sqlite3

def salvar_dados_completos_em_tabelas(db_path, df_parte1, df_parte2, df_parte3, df_parte4):
    """
    Salva os dados completos (tópico, texto, parte, relatório) em 4 tabelas dentro de um banco de dados SQLite.

    Parâmetros:
    - db_path: Caminho do banco de dados SQLite.
    - df_parte1, df_parte2, df_parte3, df_parte4: DataFrames com os dados completos (tópico, texto, parte, relatório).
    """
    # Verificar as colunas dos DataFrames
    print("Colunas do DataFrame Parte 1:", df_parte1.columns)
    print("Colunas do DataFrame Parte 2:", df_parte2.columns)
    print("Colunas do DataFrame Parte 3:", df_parte3.columns)
    print("Colunas do DataFrame Parte 4:", df_parte4.columns)

    # Conectar ao banco de dados SQLite
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    # Apagar tabelas existentes, caso existam
    cursor.execute('DROP TABLE IF EXISTS parte1_dados')
    cursor.execute('DROP TABLE IF EXISTS parte2_dados')
    cursor.execute('DROP TABLE IF EXISTS parte3_dados')
    cursor.execute('DROP TABLE IF EXISTS parte4_dados')

    # Criar novas tabelas para armazenar os dados completos
    cursor.execute('''
        CREATE TABLE parte1_dados (
            topico TEXT,
            texto TEXT,
            parte INTEGER,
            numero_relatorio INTEGER
        )
    ''')

    cursor.execute('''
        CREATE TABLE parte2_dados (
            topico TEXT,
            texto TEXT,
            parte INTEGER,
            numero_relatorio INTEGER
        )
    ''')

    cursor.execute('''
        CREATE TABLE parte3_dados (
            topico TEXT,
            texto TEXT,
            parte INTEGER,
            numero_relatorio INTEGER
        )
    ''')

    cursor.execute('''
        CREATE TABLE parte4_dados (
            topico TEXT,
            texto TEXT,
            parte INTEGER,
            numero_relatorio INTEGER
        )
    ''')

    # Função para salvar os dados completos
    def salvar_dados(df, parte):
        # Verificar se o DataFrame possui as colunas corretas
        if 'topico' not in df.columns or 'texto' not in df.columns or 'relatorio' not in df.columns:
            print(f"Erro: o DataFrame da Parte {parte} está faltando uma ou mais colunas necessárias.")
            print("Colunas encontradas:", df.columns)
            return

        # Inserir os dados na tabela correspondente
        for _, row in df.iterrows():
            cursor.execute(f'''
                INSERT INTO parte{parte}_dados (topico, texto, parte, numero_relatorio)
                VALUES (?, ?, ?, ?)
            ''', (row['topico'], row['texto'], parte, row['relatorio']))

    # Salvar os dados completos para cada parte
    salvar_dados(df_parte1, 1)
    salvar_dados(df_parte2, 2)
    salvar_dados(df_parte3, 3)
    salvar_dados(df_parte4, 4)

    # Commit das alterações e fechamento da conexão
    conn.commit()
    conn.close()

# Exemplo de uso:
salvar_dados_completos_em_tabelas('relatorio.db', df_parte1, df_parte2, df_parte3, df_parte4)

Colunas do DataFrame Parte 1: Index(['texto', 'parte', 'relatorio', 'texto_limpo'], dtype='object')
Colunas do DataFrame Parte 2: Index(['texto', 'parte', 'relatorio', 'texto_limpo'], dtype='object')
Colunas do DataFrame Parte 3: Index(['texto', 'parte', 'relatorio', 'texto_limpo'], dtype='object')
Colunas do DataFrame Parte 4: Index(['texto', 'parte', 'relatorio', 'texto_limpo'], dtype='object')
Erro: o DataFrame da Parte 1 está faltando uma ou mais colunas necessárias.
Colunas encontradas: Index(['texto', 'parte', 'relatorio', 'texto_limpo'], dtype='object')
Erro: o DataFrame da Parte 2 está faltando uma ou mais colunas necessárias.
Colunas encontradas: Index(['texto', 'parte', 'relatorio', 'texto_limpo'], dtype='object')
Erro: o DataFrame da Parte 3 está faltando uma ou mais colunas necessárias.
Colunas encontradas: Index(['texto', 'parte', 'relatorio', 'texto_limpo'], dtype='object')
Erro: o DataFrame da Parte 4 está faltando uma ou mais colunas necessárias.
Colunas encontradas: Index(['texto', 'parte', 'relatorio', 'texto_limpo'], dtype='object')